### ISSUE TITLE
Port to ROS Indigo

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_hironx#202]
This is a mid-term project. Aiming within the year 2014 might be a good goal.
- [x] Indigo-nize RTM dependencies incl. `OpenRTM-aist` (https://github.com/start-jsk/openrtm_aist_core/issues/55), `OpenHRP3`, `hrpsys`, `rtmros_common`
- [x] Indigo-nize `pr2_controllers`, or replace it with equivalent (e.g. ros_control or ROS-Industrial)
- [x] Test well on a real robot!
- [x] #348 TF issue rooted in collada-dom 
- [x] Collada reading issue (addressed in https://github.com/ros/robot_model/pull/108)
- [x] rostest passes for hrpsys and ros_bridge
- [x] MoveIt! collada issue https://github.com/start-jsk/rtmros_hironx/issues/366 --> Requires collada_dom 2.4.3 DEB version to be released
- [x] Provide upgrade instruction (Ubuntu (12.04-->14.04), ROS (H-->I), drivers (ueye. What else?)

Add up bullets to the above if any new items come up.

**Comment by 130s** [comment]
I somehow released into indigo https://github.com/ros/rosdistro/pull/7109. Tests and feedback with simulation and real robots are appreciated.

**Comment by 130s** [comment]
Moved from https://github.com/tork-a/rtmros_nextage/issues/157#issuecomment-86096424

> please also check
> - https://github.com/rdiankov/collada-dom/pull/13 
> - https://github.com/jsk-ros-pkg/jsk_model_tools/issues/99 
> 
> for indigo release, although nextage itself did not depends on collada, other hrpsys robots does.

**Comment by k-okada** [comment]
yes, you can release indigo for nextage in theory, be careful about

https://github.com/tork-a/rtmros_nextage/blob/hydro-devel/nextage_ros_bridge/launch/nextage_ros_bridge_simulation.launch#L2
-> uses collada file
https://github.com/tork-a/rtmros_nextage/blob/hydro-devel/nextage_ros_bridge/launch/nextage_ros_bridge_real.launch#L2
-> it did not set model file, so it may uses hiro's collada file

## 

◉ Kei Okada

**Comment by k-okada** [comment]
Indigo is ready for now with https://github.com/ros/robot_model/pull/108 fix, please confirm this

**Comment by 130s** [comment]
@k-okada 
> Indigo is ready for now with ros/robot_model#108 fix, please confirm this

Does this mean we have to manually re-generate *.dae files using the latest `collada_to_urdf`?

**Comment by 130s** [comment]
@k-okada 

> Indigo is ready for now with ros/robot_model#108 fix, please confirm this

Does this mean we have to manually re-generate the `NextageOpen.urdf` file using the latest `collada_to_urdf`?

**Comment by k-okada** [comment]
if you already have urdf, you do not have to re-generate one.
if you have dae on robot_description, previous robot_model fail to load 
that data and segfaults, for example robot_state_publisher did not work.

## 

◉ Kei Okada

**Comment by 130s** [comment]
Thank you for the clarification, I finally understand what https://github.com/start-jsk/rtmros_hironx/issues/202#issuecomment-88318074 meant. 
Now I think we're ready to move on to running tests on Indigo.

**Comment by k-okada** [comment]
sorry for confusion, see
https://github.com/ros/robot_model/pull/108#issuecomment-96960419 for how
did I test for that.

## 

◉ Kei Okada

**Comment by 130s** [comment]
On Indigo I confirmed that https://github.com/ros/robot_model/pull/108 bypasses the following error.

```
$ dpkg -p ros-indigo-robot-model |grep Ver
Version: 1.11.7-0trusty-20150501-154913-0700

$ roslaunch nextage_ros_bridge nextage_ros_bridge_real.launch 
:
[ INFO] [1432638009.561789569]: [HrpsysJointTrajectoryBridge] @Initilize name : HrpsysJointTrajectoryBridge0 done
process[hrpsys_state_publisher-5]: started with pid [4758]
process[hrpsys_ros_diagnostics-6]: started with pid [4773]
[ERROR] [1432638009.736530237]: COLLADA error: Trying to load an invalid COLLADA version for this DOM build!

process[diagnostic_aggregator-7]: started with pid [4778]
[ERROR] [1432638009.746596690]: COLLADA error: Failed to load XML document from memory

[hrpsys_state_publisher-5] process has died [pid 4758, exit code -11, cmd /opt/ros/indigo/lib/robot_state_publisher/state_publisher __name:=hrpsys_state_publisher __log:=/home/n130s/.ros/log/5f8a3efc-0396-11e5-9573-80fa5b08d1d8/hrpsys_state_publisher-5.log].
log file: /home/n130s/.ros/log/5f8a3efc-0396-11e5-9573-80fa5b08d1d8/hrpsys_state_publisher-5*.log
```

**Comment by k-okada** [comment]
So, can we close this issue?

**Comment by 130s** [comment]
I'm afraid `rostest` still fails.

```
$ rostest hironx_ros_bridge test-hironx-ros-bridge.test 
... logging to /home/rospasta/.ros/log/rostest-tork-kudu1-6001.log
[ROSUNIT] Outputting test results to /home/rospasta/.ros/test_results/hironx_ros_bridge/rostest-test_test-hironx-ros-bridge.xml
omniORB: Failed to bind to address :: port 2809. Address in use?
omniORB: Error: Unable to create an endpoint of this description: giop:tcp::2809
Failed to initialise the ORB / POA: INITIALIZE_TransportError
Is omniNames already running?
ready
loading file:///home/rospasta/cws_hironxo/src/start-jsk/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
loading /home/rospasta/cws_hironxo/src/start-jsk/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
Collada Warning: fill asset info
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: joint HEAD_JOINT1 has axis: 0.000000 1.000000 0.000000
Collada Warning: joint HEAD_JOINT0 has axis: 0.000000 0.000000 1.000000
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: joint RHAND_JOINT1 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint RHAND_JOINT0 has axis: 0.000000 0.000000 1.000000
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: joint RHAND_JOINT3 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint RHAND_JOINT2 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint RARM_JOINT5 has axis: 1.000000 0.000000 0.000000
Collada Warning: joint RARM_JOINT4 has axis: 0.000000 1.000000 0.000000
Collada Warning: joint RARM_JOINT3 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint RARM_JOINT2 has axis: 0.000000 1.000000 0.000000
Collada Warning: joint RARM_JOINT1 has axis: 0.000000 1.000000 0.000000
Collada Warning: joint RARM_JOINT0 has axis: 0.000000 0.000000 1.000000
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: joint LHAND_JOINT1 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint LHAND_JOINT0 has axis: 0.000000 0.000000 1.000000
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: joint LHAND_JOINT3 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint LHAND_JOINT2 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint LARM_JOINT5 has axis: 1.000000 0.000000 0.000000
Collada Warning: joint LARM_JOINT4 has axis: 0.000000 1.000000 0.000000
Collada Warning: joint LARM_JOINT3 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint LARM_JOINT2 has axis: 0.000000 1.000000 0.000000
Collada Warning: joint LARM_JOINT1 has axis: 0.000000 1.000000 0.000000
Collada Warning: joint LARM_JOINT0 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint CHEST_JOINT0 has axis: 0.000000 0.000000 1.000000
The model was successfully loaded ! 
Warning: Model HiroNX has empty joint ID in the valid IDs.
Loading body customizer "/opt/ros/indigo/share/OpenHRP-3.1/customizer/libSampleCustomizer.so" for springJoint
loading file:///opt/ros/indigo/share/OpenHRP-3.1/idl/../../..//share/OpenHRP-3.1/sample/model/longfloor.wrl
Humanoid node
Joint node WAIST
  Segment node BODY
The model was successfully loaded ! 
Collada Warning: fill asset info
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: joint HEAD_JOINT1 has axis: 0.000000 1.000000 0.000000
Collada Warning: joint HEAD_JOINT0 has axis: 0.000000 0.000000 1.000000
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: joint RHAND_JOINT1 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint RHAND_JOINT0 has axis: 0.000000 0.000000 1.000000
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: joint RHAND_JOINT3 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint RHAND_JOINT2 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint RARM_JOINT5 has axis: 1.000000 0.000000 0.000000
Collada Warning: joint RARM_JOINT4 has axis: 0.000000 1.000000 0.000000
Collada Warning: joint RARM_JOINT3 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint RARM_JOINT2 has axis: 0.000000 1.000000 0.000000
Collada Warning: joint RARM_JOINT1 has axis: 0.000000 1.000000 0.000000
Collada Warning: joint RARM_JOINT0 has axis: 0.000000 0.000000 1.000000
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: joint LHAND_JOINT1 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint LHAND_JOINT0 has axis: 0.000000 0.000000 1.000000
Collada Warning: generate normals from vertices
Collada Warning: generate normals from vertices
Collada Warning: joint LHAND_JOINT3 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint LHAND_JOINT2 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint LARM_JOINT5 has axis: 1.000000 0.000000 0.000000
Collada Warning: joint LARM_JOINT4 has axis: 0.000000 1.000000 0.000000
Collada Warning: joint LARM_JOINT3 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint LARM_JOINT2 has axis: 0.000000 1.000000 0.000000
Collada Warning: joint LARM_JOINT1 has axis: 0.000000 1.000000 0.000000
Collada Warning: joint LARM_JOINT0 has axis: 0.000000 0.000000 1.000000
Collada Warning: joint CHEST_JOINT0 has axis: 0.000000 0.000000 1.000000
The model was successfully loaded ! 
Warning: Model HiroNX has empty joint ID in the valid IDs.
Loading body customizer "/opt/ros/indigo/share/OpenHRP-3.1/customizer/libSampleCustomizer.so" for springJoint
cache found for /home/rospasta/cws_hironxo/src/start-jsk/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
duplicated sensor Id is specified(id = 1, name = rhsensor)
duplicated sensor Id is specified(id = 0, name = lhsensor)
Warning: Model HiroNX has empty joint ID in the valid IDs.
[ INFO] [1432652402.924005241]: [HrpsysJointTrajectoryBridge] @Initilize name : HrpsysJointTrajectoryBridge0 done
[ WARN] [1432652403.112499707]: [HrpsysSeqStateROSBridge] use_hrpsys_time
/opt/ros/indigo/share/hrpsys_ros_bridge/scripts/diagnostics.py:75: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  pub = rospy.Publisher('diagnostics', DiagnosticArray)
[ INFO] [1432652403.237586735]: [HrpsysSeqStateROSBridge] @Initilize name : HrpsysSeqStateROSBridge0
cache found for /home/rospasta/cws_hironxo/src/start-jsk/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
Warning: Model HiroNX has empty joint ID in the valid IDs.
Loading body customizer "/opt/ros/indigo/share/OpenHRP-3.1/customizer/libSampleCustomizer.so" for springJoint
cache found for /home/rospasta/cws_hironxo/src/start-jsk/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
duplicated sensor Id is specified(id = 1, name = rhsensor)
duplicated sensor Id is specified(id = 0, name = lhsensor)
Warning: Model HiroNX has empty joint ID in the valid IDs.
0 physical force sensor : lhsensor
1 physical force sensor : rhsensor
[ INFO] [1432652403.246350761]: [HrpsysSeqStateROSBridge] Loaded HiroNX
[ INFO] [1432652403.246606901]: [HrpsysSeqStateROSBridge] @Initilize name : HrpsysSeqStateROSBridge0 done
/opt/ros/indigo/share/hrpsys_ros_bridge/scripts/hrpsys_profile.py:88: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  pub = rospy.Publisher('diagnostics', DiagnosticArray)
[sensor_ros_bridge_connect.py]  start
configuration ORB with localhost:2809
configuration ORB with localhost:2809
[hrpsys.py] waiting ModelLoader
[hrpsys.py] start hrpsys
[hrpsys.py] finding RTCManager and RobotHardware
[rtmlaunch] starting...  /opt/ros/indigo/share/hrpsys_ros_bridge/launch/hrpsys_ros_bridge.launch
[rtmlaunch] RTCTREE_NAMESERVERS localhost:2809 localhost:2809
[rtmlaunch] SIMULATOR_NAME HiroNX(Robot)0
[rtmlaunch] check connection/activation
;;
;; Could not open /dev/console for writing.
;;
open: Permission denied
cache found for file:///home/rospasta/cws_hironxo/src/start-jsk/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
Warning: Model HiroNX has empty joint ID in the valid IDs.
Loading body customizer "/opt/ros/indigo/share/OpenHRP-3.1/customizer/libSampleCustomizer.so" for springJoint
prop[collision_pair] ->RARM_JOINT2:LARM_JOINT2 RARM_JOINT3:LARM_JOINT3 RARM_JOINT4:LARM_JOINT4 RARM_JOINT5:LARM_JOINT5
check collisions between RARM_JOINT2 and LARM_JOINT2
check collisions between RARM_JOINT3 and LARM_JOINT3
check collisions between RARM_JOINT4 and LARM_JOINT4
check collisions between RARM_JOINT5 and LARM_JOINT5
[rtmlaunch] starting...  /opt/ros/indigo/share/hrpsys_ros_bridge/launch/collision_detector.launch
[rtmlaunch] RTCTREE_NAMESERVERS localhost:2809 localhost:2809
[rtmlaunch] SIMULATOR_NAME HiroNX(Robot)0
[rtmlaunch] check connection/activation
[sensor_ros_bridge_connect.py] wait for RTCmanager : tork-kudu1
[sensor_ros_bridge_connect.py] wait for HiroNX(Robot)0 : <hrpsys.rtm.RTcomponent instance at 0x7f9e91a4a050> ( timeout 0 < 10)
[sensor_ros_bridge_connect.py] findComps -> RobotHardware : <hrpsys.rtm.RTcomponent instance at 0x7f9e91a4a050> isActive? = True 
[sensor_ros_bridge_connect.py] simulation_mode : True
[hrpsys.py] wait for RTCmanager : None
[hrpsys.py] wait for HiroNX(Robot)0 : <hrpsys.rtm.RTcomponent instance at 0x7fdbbd1ccef0> ( timeout 0 < 10)
[hrpsys.py] findComps -> RobotHardware : <hrpsys.rtm.RTcomponent instance at 0x7fdbbd1ccef0> isActive? = True 
[hrpsys.py] simulation_mode : True
[hrpsys.py]   bodyinfo URL = file:///home/rospasta/cws_hironxo/src/start-jsk/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
cache found for file:///home/rospasta/cws_hironxo/src/start-jsk/rtmros_hironx/hironx_ros_bridge/models/kawada-hironx.dae
[hrpsys.py] creating components
[hrpsys.py]   eval : [self.seq, self.seq_svc, self.seq_version] = self.createComp("SequencePlayer","seq")
/opt/ros/indigo/share/hrpsys_ros_bridge/scripts/collision_state.py:181: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  pub_diagnostics = rospy.Publisher('diagnostics', DiagnosticArray)
/opt/ros/indigo/share/hrpsys_ros_bridge/scripts/collision_state.py:182: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  pub_collision = rospy.Publisher('collision_detector_marker_array', MarkerArray)
configuration ORB with localhost:2809
[WARN] [WallTime: 1432652404.857500] [0.000000] CollisionDetector(CollisionDetector0) is not activated, waiting...
[sensor_ros_bridge_connect.py]   wait for  HrpsysSeqStateROSBridge0  :  <hrpsys.rtm.RTcomponent instance at 0x7f9e91a764d0>
[WARN] [WallTime: 1432652405.860415] [0.000000] CollisionDetector(CollisionDetector0) is not activated, waiting...
[WARN] [WallTime: 1432652406.864995] [0.000000] CollisionDetector(CollisionDetector0) is not activated, waiting...
[WARN] [WallTime: 1432652407.869541] [0.000000] CollisionDetector(CollisionDetector0) is not activated, waiting...
[WARN] [WallTime: 1432652408.872688] [0.000000] CollisionDetector(CollisionDetector0) is not activated, waiting...
[WARN] [WallTime: 1432652409.875767] [0.000000] CollisionDetector(CollisionDetector0) is not activated, waiting...
[WARN] [WallTime: 1432652410.882828] [0.000000] CollisionDetector(CollisionDetector0) is not activated, waiting...
[WARN] [WallTime: 1432652411.888029] [0.000000] CollisionDetector(CollisionDetector0) is not activated, waiting...
[WARN] [WallTime: 1432652412.894426] [0.000000] CollisionDetector(CollisionDetector0) is not activated, waiting...
[WARN] [WallTime: 1432652413.902366] [0.000000] CollisionDetector(CollisionDetector0) is not activated, waiting...
[ERROR] [WallTime: 1432652414.903483] [0.000000] Could not found CollisionDetector, exiting...
[ INFO] [1432652425.875176859]: [HrpsysSeqStateROSBridge] @onFinalize : HrpsysSeqStateROSBridge0
terminate called after throwing an instance of 'CORBA::OBJECT_NOT_EXIST'
terminate called after throwing an instance of 'class_loader::LibraryUnloadException'
  what():  Attempt to unload library that class_loader is unaware of.
testjoint_states_test ... ok

[ROSTEST WARNINGS]--------------------------------------------------------------

 * unrecognized tag rtconnect
 * unrecognized tag rtconnect
 * unrecognized tag rtconnect
 * unrecognized tag rtconnect
 * unrecognized tag rtconnect
 * unrecognized tag rtconnect
 * unrecognized tag rtconnect
 * unrecognized tag rtconnect
 * unrecognized tag rtconnect
 * unrecognized tag rtconnect
 * unrecognized tag rtactivate
 * unrecognized tag rtactivate
 * unrecognized tag rtactivate
 * unrecognized tag rtactivate
 * unrecognized tag rtactivate
 * unrecognized tag rtactivate
 * unrecognized tag rtconnect
 * unrecognized tag rtconnect
 * unrecognized tag rtactivate

[ROSTEST]-----------------------------------------------------------------------

[hironx_ros_bridge.rosunit-joint_states_test/test_hz][FAILURE]------------------
no messages before timeout
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/share/rostest/nodes/hztest/hztest", line 117, in test_hz
    self._test_hz(hz, hzerror, topic, test_duration, wait_time)
  File "/opt/ros/indigo/share/rostest/nodes/hztest/hztest", line 152, in _test_hz
    self.assert_(self.message_received, "no messages before timeout")
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------


SUMMARY
 * RESULT: FAIL
 * TESTS: 1
 * ERRORS: 0
 * FAILURES: 1

rostest log file is in /home/rospasta/.ros/log/rostest-tork-kudu1-6001.log
```

**Comment by k-okada** [comment]
On Wed, May 27, 2015 at 12:04 AM, Isaac I.Y. Saito <notifications@github.com

> wrote:
> 
> terminate called after throwing an instance of 'CORBA::OBJECT_NOT_EXIST'
> terminate called after throwing an instance of
> 'class_loader::LibraryUnloadException' what(): Attempt to unload library
> that class_loader is unaware of

did you installed ros-indigo-collada-parser? pleas try if
https://github.com/ros/robot_model/pull/108#issuecomment-96960419 works

## 

◉ Kei Okada

**Comment by 130s** [comment]
As I commented above, https://github.com/start-jsk/rtmros_hironx/issues/202#issuecomment-105489479 https://github.com/ros/robot_model/pull/108 works. But the problem I posted https://github.com/start-jsk/rtmros_hironx/issues/202#issuecomment-105555894 is `rostest` that uses DEB afaik, and https://github.com/ros/robot_model/issues/108 is not yet released. I asked the new release in https://github.com/ros/robot_model/issues/109.

**Comment by 130s** [comment]
https://github.com/start-jsk/rtmros_hironx/issues/366 needs fixed.

**Comment by 130s** [comment]
Based on [this conversation](https://groups.google.com/forum/#!topic/rtm-ros-robotics/qrDWvnjxrV0), there's a user group that wants to use Hydro version until September. Also, because September is also the last month of the 1st half in the fiscal year of Japan where some core maintainers are based in, I think making a big change in the month October makes sense.

**Comment by 130s** [comment]
Newer version of `robot_model` that contains https://github.com/ros/robot_model/pull/108 is released into Indigo.
So only remaining is https://github.com/rdiankov/collada-dom/issues/16?

**Comment by 130s** [comment]
And just an FYI, Hydro build is finally terminated https://github.com/ros/rosdistro/pull/9469.

**Comment by 130s** [comment]
> So only remaining is rdiankov/collada-dom#16?

This is now checked. Ready for Indigo.

**Comment by 130s** [comment]
Another task: Provide upgrade instruction (Ubuntu (12.04-->14.04), ROS (H-->I), drivers (ueye. What else?)

**Comment by 130s** [comment]
Instruction is done at https://github.com/start-jsk/rtmros_hironx/issues/396, so is the announcement.
